databases:
  - name: THE_NAME
    databaseName: DATABASE_NAME
    user: mana
    region: singapore

services:
  - type: web
    name: gamefolio
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: DATABASE_NAME
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
